name: kseg
description: A Flutter package that detects and segments different scripts within a string (e.g., Khmer and Latin), enabling distinct styling for each script.
version: 1.0.0
repository: https://github.com/sovanken/kseg
homepage: https://github.com/sovanken/kseg

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
